### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by gnperdue** [AleksCipri/DeepMergeDomainAdaptation#7]
Might be good to put the requirements.txt file back - or is it just PyTorch, basically? Is the code using any "niche" libraries?

Also, it might be neat to put a copy of a "working" Colab notebook here (just save as a ipynb and stick it in a "demos" folder).

**Comment by AleksCipri** [comment]
Yes I'll make requirements file for sure. Just didn't get to that yet. We have some notebooks in or branches, but currently we have nothing in our master branch, notebooks or py files. But We'll put something in the master branch soon! Also, it is more less just pytorch and the usual stuff. Nothin very fancy.

**Comment by gnperdue** [comment]
We got something in a while ago but forgot to close this...
